import {useEffect,useMemo,useRef,useState} from 'react';
import {api,post} from './api';
import type {Relic,Reward,RunSession} from './types';

const eras=['Lith','Meso','Neo','Axi'];
export function Display(){
 const [relics,setRelics]=useState<Relic[]>([]),[slots,setSlots]=useState<(string|null)[]>([null,null,null,null]),[run,setRun]=useState<RunSession|null>(null),[chosen,setChosen]=useState<Reward|null>(null),[tx,setTx]=useState<string|null>(null),[error,setError]=useState('');
 const lock=useRef(false); useEffect(()=>{api<Relic[]>('/catalog/relics').then(setRelics).catch(e=>setError(e.message))},[]);
 const available=useMemo(()=>relics.reduce<Record<string,Relic[]>>((a,r)=>((a[r.era]??=[]).push(r),a),{}),[relics]);
 async function begin(){const ids=slots.filter(Boolean) as string[];if(!ids.length)return;try{setRun(await post('/runs',{relic_ids:ids}));setChosen(null);setTx(null)}catch(e){setError((e as Error).message)}}
 async function confirm(){if(!run||!chosen||lock.current)return;lock.current=true;try{const result=await post<{transaction_id:string}>(`/runs/${run.id}/confirm`,{item_id:chosen.id,idempotency_key:`${run.id}-${chosen.id}`});setTx(result.transaction_id);setRun({...run,state:'confirmed',chosen_item_id:chosen.id})}catch(e){setError((e as Error).message)}finally{lock.current=false}}
 async function undo(){if(!tx)return;await post(`/transactions/${tx}/undo`);setRun(run?{...run,state:'open',chosen_item_id:null}:null);setChosen(null);setTx(null)}
 if(!run)return <main className="display picker"><header><div><span className="eyebrow">VOID FISSURE</span><h1>Squad Relics</h1></div><a href="/manage">Manage</a></header>{error&&<div className="error">{error}</div>}<div className="slot-grid">{slots.map((selected,i)=><section className="slot" key={i}><div className="slot-label">SQUAD {i+1}</div><div className="era-tabs">{eras.map(era=><button key={era} disabled={!available[era]?.length} className={selected&&relics.find(r=>r.id===selected)?.era===era?'active':''} onClick={()=>setSlots(s=>s.map((v,n)=>n===i?(available[era]?.[0]?.id??null):v))}>{era}</button>)}</div><div className="relic-list">{selected&&available[relics.find(r=>r.id===selected)!.era]?.map(r=><button className={r.id===selected?'active':''} onClick={()=>setSlots(s=>s.map((v,n)=>n===i?r.id:v))} key={r.id}>{r.code}</button>)}</div></section>)}</div><button className="begin" disabled={!slots.some(Boolean)} onClick={begin}>Show Rewards</button></main>;
 return <main className="display rewards"><header><button onClick={()=>setRun(null)}>← Relics</button><div><span className="eyebrow">SELECTED IN GAME</span><h1>Choose reward to record</h1></div><span className="round-state">{run.state}</span></header><div className="reward-grid">{run.columns.map((col,i)=><section key={`${col.id}-${i}`}><h2>{col.era} {col.code}<small>SQUAD {i+1}</small></h2>{col.rewards.map(r=><button disabled={run.state==='confirmed'} className={`reward ${r.rarity} ${chosen?.id===r.id?'chosen':''}`} key={r.id} onClick={()=>setChosen(r)}><span className="reward-name">{r.name}</span><span className="reward-stats"><b>{r.owned}/{r.required||'✓'}</b><i>{r.rarity}</i><i>{r.availability}</i><i>{r.ducats}◈</i><i>{r.market_median==null?'—':`${r.market_median}p`}</i></span></button>)}</section>)}</div>{chosen&&run.state==='open'&&<button className="confirm" onClick={confirm}>Confirm {chosen.name} <span>+1 part</span></button>}{run.state==='confirmed'&&<div className="confirmed">Reward recorded <button onClick={undo}>Undo</button><button onClick={()=>setRun(null)}>Next round</button></div>}</main>
}
