import {useEffect,useMemo,useState} from 'react';
import {api,patch,post} from './api';
import type {Equipment} from './types';

const ownedPlatinum=(e:Equipment)=>e.parts.reduce((total,p)=>total+p.owned*(p.market_median??0),0);
function priceAge(at:string|null){if(!at)return '';const hours=(Date.now()-Date.parse(at))/36e5;return hours<1?`${Math.max(1,Math.round(hours*60))}m ago`:hours<48?`${Math.round(hours)}h ago`:`${Math.round(hours/24)}d ago`}

export function Manage(){
 const [equipment,setEquipment]=useState<Equipment[]>([]),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[hideMastered,setHideMastered]=useState(false),[missing,setMissing]=useState('all'),[sort,setSort]=useState('name'),[platinumThreshold,setPlatinumThreshold]=useState(20),[open,setOpen]=useState<string|null>(null),[syncing,setSyncing]=useState(false),[error,setError]=useState(''),[prices,setPrices]=useState<{total:number;fresh:number;running:boolean}|null>(null);
 const load=()=>api<Equipment[]>('/collection').then(setEquipment).catch(e=>setError(e.message));
 useEffect(()=>{const status=()=>void api<{total:number;fresh:number;running:boolean}>('/market/status').then(setPrices).catch(()=>{});status();const timer=window.setInterval(status,30000);return ()=>window.clearInterval(timer)},[]);
 useEffect(()=>{void load();void api<{platinum_highlight_threshold:number}>('/settings').then(value=>setPlatinumThreshold(value.platinum_highlight_threshold)).catch(e=>setError(e.message))},[]);
 const filtered=useMemo(()=>equipment.filter(e=>(filter==='all'||e.type===filter)&&(!hideMastered||!e.mastered)&&(missing==='all'||(missing==='0'?e.ready:missing==='1'?e.missing_count===1:missing==='2'?e.missing_count===2:e.missing_count>2))&&`${e.name} ${e.parts.map(p=>p.name).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='closest'?a.missing_count-b.missing_count||a.name.localeCompare(b.name):sort==='furthest'?b.missing_count-a.missing_count||a.name.localeCompare(b.name):sort==='platinum'?ownedPlatinum(b)-ownedPlatinum(a)||a.name.localeCompare(b.name):a.name.localeCompare(b.name)),[equipment,query,filter,hideMastered,missing,sort]);
 async function qty(id:string,delta:number){try{await patch(`/inventory/${id}`,{delta});load()}catch(e){setError((e as Error).message)}}
 async function build(e:Equipment){if(!confirm(`Build ${e.name}? This removes one set of parts from your inventory.`))return;try{await post(`/equipment/${e.id}/build`);load()}catch(err){setError((err as Error).message)}}
 async function toggleMastered(id:string,value:number){await patch(`/equipment/${id}`,{mastered:!value});load()}
 async function upload(path:string,file:File){const body=new FormData();body.append('file',file);const r=await fetch(`/api/v1${path}`,{method:'POST',body});if(!r.ok)setError((await r.json()).detail);else load()}
 async function refresh(){setSyncing(true);try{await post('/catalog/relics/refresh');await load()}catch(e){setError((e as Error).message)}finally{setSyncing(false)}}
 async function saveThreshold(){try{await patch('/settings',{platinum_highlight_threshold:platinumThreshold})}catch(e){setError((e as Error).message)}}
 return <main className="manage">
   <header><div><span className="eyebrow">ORBITER ARCHIVE</span><h1>Prime Collection</h1></div><a className="run-link" href="/display">Open Run Mode →</a></header>
   {error&&<div className="error" onClick={()=>setError('')}>{error} ×</div>}
   <section className="toolbar"><input autoFocus placeholder="Search equipment or parts…" value={query} onChange={e=>setQuery(e.target.value)}/><button onClick={refresh} disabled={syncing}>{syncing?'Updating…':'Refresh catalog'}</button><a href="/api/v1/inventory.csv" download>Export CSV</a><a href="/api/v1/backup" download>JSON backup</a><label>Import CSV<input hidden type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&upload('/inventory/import',e.target.files[0])}/></label><label>Restore<input hidden type="file" accept=".json" onChange={e=>e.target.files?.[0]&&upload('/backup/restore',e.target.files[0])}/></label></section>
   <nav className="equipment-filters"><label>Type<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All Prime</option><option value="warframe">Warframes</option><option value="archwing">Archwings</option><option value="primary">Primary</option><option value="secondary">Secondary</option><option value="melee">Melee</option><option value="archgun">Archguns</option><option value="companion">Companions</option><option value="companion_weapon">Companion weapons</option></select></label><label>Missing parts<select value={missing} onChange={e=>setMissing(e.target.value)}><option value="all">Any</option><option value="0">Complete set</option><option value="1">1 missing</option><option value="2">2 missing</option><option value="3+">More than 2</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="closest">Closest first</option><option value="furthest">Most missing first</option><option value="platinum">Platinum (owned)</option></select></label><label className="mastered-toggle"><input type="checkbox" checked={hideMastered} onChange={e=>setHideMastered(e.target.checked)}/> Hide mastered</label><label className="platinum-setting">Highlight Platinum <output>{platinumThreshold}p+</output><input type="range" min="5" max="100" step="5" value={platinumThreshold} onChange={e=>setPlatinumThreshold(Number(e.target.value))} onPointerUp={()=>void saveThreshold()} onKeyUp={()=>void saveThreshold()} onBlur={()=>void saveThreshold()}/></label><span className="result-count">{prices&&<span className="price-status" title={prices.running?'Prices refresh slowly in the background':'Background price refresh is off'}>Prices {prices.fresh}/{prices.total} current · </span>}{filtered.length} shown</span></nav>
   <div className="cards">{filtered.map(e=><article className="equipment" key={e.id}>
    <div className="equipment-title"><div><span className={`status ${e.availability}`}>{e.type.replace('_',' ')} · {e.availability}</span><h2>{e.name}</h2><small>{e.ready?'SET COMPLETE':`${e.missing_count} REQUIRED`} · {e.surplus_sets} complete set{e.surplus_sets===1?'':'s'}{ownedPlatinum(e)>0&&` · ${Math.round(ownedPlatinum(e))}p owned`}</small></div><div className="checks">{e.ready&&<button onClick={()=>build(e)}>Build</button>}<button className={e.mastered?'on':''} onClick={()=>toggleMastered(e.id,e.mastered)}>mastered</button><button className={open===e.id?'on':''} onClick={()=>setOpen(open===e.id?null:e.id)}>{open===e.id?'Hide parts':'Parts'}</button></div></div>
    {(open===e.id||query.length>1)&&<div className="parts">{e.parts.map(p=><div className="part" key={p.id}><div><b>{p.name}</b><span className={`rarity ${p.availability}`}>{p.availability}</span></div><div className="value"><span>{p.ducats} ◈</span><span title={p.market_updated_at?`Price from ${priceAge(p.market_updated_at)}`:'Not priced yet'}>{p.market_median==null?'—':`${p.market_median}p`}{p.market_updated_at&&<i className="price-age"> · {priceAge(p.market_updated_at)}</i>}</span></div><div className="stepper"><button aria-label={`Remove ${p.name}`} onClick={()=>qty(p.id,-1)}>−</button><strong>{p.owned}<i>/{p.required}</i></strong><button aria-label={`Add ${p.name}`} onClick={()=>qty(p.id,1)}>+</button></div></div>)}</div>}
   </article>)}</div>
 </main>
}
